# Generated by Django 5.2 on 2025-04-24 16:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la Vacante')),
                ('descripcion', models.TextField(verbose_name='Descripción del Puesto')),
                ('empresa', models.CharField(max_length=150, verbose_name='Nombre de la Empresa')),
                ('ubicacion', models.CharField(max_length=100, verbose_name='Ubicación')),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario (Opcional)')),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Publicación')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Está Activa?')),
            ],
            options={
                'verbose_name': 'Vacante',
                'verbose_name_plural': 'Vacantes',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
